version: '3.9'

services:
  frontend:
    container_name: ai4artist
    image: nightcrawlers512/ai4artist:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=https://api.mangahay.top/
      - NEXT_PUBLIC_SOCKET_URL=https://socket.mangahay.top/
    ports:
      - "8080:8080"
