version: '3.9'

services:
  frontend:
    container_name: ai4artist
    image: nightcrawlers512/ai4artist:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    ports:
      - "8080:8080"
