name: SSH to server ubuntu and remove container and image
description: SSH to server ubuntu and remove container and image

inputs:
  ssh-private-key: 
    description: SSH private key to access
    required: true
  ssh-username: 
    description: Username for SSH connection
    required: true
    default: "root"
  ssh-host: 
    description: IPv4 address of server
    required: true
  ssh-port:
    description: Port for SSH connection
    required: true
    default: "22"

runs:
 using: composite
 steps:
  - name: SSH to server ubuntu and remove container and image
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ inputs.ssh-host }}
      username: ${{ inputs.ssh-username }}
      key: ${{ inputs.ssh-private-key }}
      port: ${{ inputs.ssh-port }}
      script: |
        cd /artist_project/AI4Artists
        docker stop ai4artists || true
        docker rm ai4artists || true
        docker rmi nightcrawlers512/ai4artist:main || true
        docker compose up -d
        sleep 10
        docker exec -i ai4artists bash << 'EOF'
        