import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Suspense } from "react"
import Loading from "@/components/Loading"
import { StoreProvider } from "@/store/StoreProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "AI4Artists",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </body>
      </html>
    </StoreProvider>
  )
}
